#!/usr/bin/env bash
# Installer step 1: creates .env with strong random secrets (no default accounts or passwords).
#
#   ./scripts/generate-env.sh            create .env if it does not exist
#   ./scripts/generate-env.sh --force    regenerate (existing .env is backed up)
#
# Generated passwords are 32 random characters mixing upper/lower case, digits and symbols.
# The file is created with mode 600 (readable only by the installing user).
set -euo pipefail

# Project root: next to the script inside the offline bundle, its parent in the repository
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
[ -f "$ROOT_DIR/docker-compose.yml" ] || ROOT_DIR="$(dirname "$ROOT_DIR")"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"

if [ -f "$ENV_FILE" ] && [ "${1:-}" != "--force" ]; then
    echo ".env already exists at $ENV_FILE (use --force to regenerate)." >&2
    exit 0
fi
if [ -f "$ENV_FILE" ]; then
    cp -p "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
fi

# Random string of the given length that always contains every character class.
random_secret() {
    local len="$1" s
    while :; do
        s="$(LC_ALL=C tr -dc 'A-Za-z0-9_%+=.,-' < /dev/urandom | head -c "$len")"
        [[ "$s" =~ [A-Z] && "$s" =~ [a-z] && "$s" =~ [0-9] && "$s" =~ [_%+=.,-] ]] && break
    done
    printf '%s' "$s"
}

random_alnum() {
    LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c "$1"
}

read -r -p "Hostname or IP users will open (TLS certificate name) [library.local]: " TLS_CN || true
TLS_CN="${TLS_CN:-library.local}"
read -r -p "HTTPS port users will open [3000]: " PUBLIC_PORT || true
PUBLIC_PORT="${PUBLIC_PORT:-3000}"
read -r -p "E-mail of the first super admin (becomes SUPER_ADMIN at first login): " ADMIN_EMAIL || true
read -r -p "Organization name shown in the security notice [سامانه کتابخانه هوشمند]: " ORG_NAME || true
ORG_NAME="${ORG_NAME:-سامانه کتابخانه هوشمند}"

if [ "$PUBLIC_PORT" = "443" ]; then
    PUBLIC_URL="https://$TLS_CN"
else
    PUBLIC_URL="https://$TLS_CN:$PUBLIC_PORT"
fi

umask 077
cat > "$ENV_FILE" <<ENV
# Generated by scripts/generate-env.sh on $(date -Iseconds). Keep this file secret (mode 600).

# ── Database ────────────────────────────────────────────────
DB_NAME=library_db
# Schema owner: used only for migrations
DB_USER=library_owner
DB_PASSWORD=$(random_secret 32)
# Runtime account: data access only (least privilege)
DB_APP_USER=library_app
DB_APP_PASSWORD=$(random_secret 32)

# Keycloak's own database account
KC_DB_USER=keycloak
KC_DB_PASSWORD=$(random_secret 32)

# ── Identity provider (Keycloak) ────────────────────────────
# Exactly the URL users type in the browser (scheme, host and port)
APP_PUBLIC_URL=$PUBLIC_URL
OIDC_CLIENT_SECRET=$(random_secret 48)
# Temporary Keycloak administrator: replace with a personal admin after first start
KC_BOOTSTRAP_ADMIN_USERNAME=kc-bootstrap-$(random_alnum 6)
KC_BOOTSTRAP_ADMIN_PASSWORD=$(random_secret 32)
BOOTSTRAP_SUPER_ADMIN_EMAIL=$ADMIN_EMAIL
ORGANIZATION_NAME=$ORG_NAME

# ── Session cookie encryption (AES-256 key, base64) ─────────
SESSION_COOKIE_KEY=$(head -c 32 /dev/urandom | base64 | tr -d '\n')

# ── Network / TLS ───────────────────────────────────────────
FRONTEND_PORT=$PUBLIC_PORT
TLS_COMMON_NAME=$TLS_CN
TZ=Asia/Tehran
ENV
chmod 600 "$ENV_FILE"

echo "Created $ENV_FILE (mode 600)."
echo "Next: docker compose up -d --build"
echo "Users open: $PUBLIC_URL"
