#!/usr/bin/env bash
# Installer step 1: creates .env with strong random secrets (no default accounts or passwords).
#
#   ./scripts/generate-env.sh            create .env if it does not exist
#   ./scripts/generate-env.sh --force    regenerate (existing .env is backed up)
#
# Generated passwords are 32 random characters mixing upper/lower case, digits and symbols.
# The file is created with mode 600 (readable only by the installing user).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"

if [ -f "$ENV_FILE" ] && [ "${1:-}" != "--force" ]; then
    echo ".env already exists at $ENV_FILE (use --force to regenerate)." >&2
    exit 0
fi
if [ -f "$ENV_FILE" ]; then
    cp -p "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
fi

# Random string of the given length that always contains every character class.
random_secret() {
    local len="$1" s
    while :; do
        s="$(LC_ALL=C tr -dc 'A-Za-z0-9_%+=.,-' < /dev/urandom | head -c "$len")"
        [[ "$s" =~ [A-Z] && "$s" =~ [a-z] && "$s" =~ [0-9] && "$s" =~ [_%+=.,-] ]] && break
    done
    printf '%s' "$s"
}

read -r -p "Hostname or IP users will open (TLS certificate name) [library.local]: " TLS_CN || true
TLS_CN="${TLS_CN:-library.local}"

umask 077
cat > "$ENV_FILE" <<ENV
# Generated by scripts/generate-env.sh on $(date -Iseconds). Keep this file secret (mode 600).

# ── Database ────────────────────────────────────────────────
DB_NAME=library_db
# Schema owner: used only for migrations
DB_USER=library_owner
DB_PASSWORD=$(random_secret 32)
# Runtime account: data access only (least privilege)
DB_APP_USER=library_app
DB_APP_PASSWORD=$(random_secret 32)

# ── Application secrets ─────────────────────────────────────
JWT_SECRET=$(random_secret 64)

# ── Network / TLS ───────────────────────────────────────────
FRONTEND_PORT=3000
TLS_COMMON_NAME=$TLS_CN
TZ=Asia/Tehran
ENV
chmod 600 "$ENV_FILE"

echo "Created $ENV_FILE (mode 600)."
echo "Next: docker compose up -d --build"
